---
title: "Hands-on Exercise 1"
author: "Oscar Ricardo Moreno Gonzalez"
date: "January 10, 2026"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# Overview

This is my first attempt to create the course website.

# Getting Started

## Install and launching R packages

The code chunk below uses p_load() of pacman package to check if tidyverse packages are installed in the computer. If they are, then they will be launched into R.

```{r}
pacman::p_load(tidyverse) 
```

## The Data

Importing the data

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

# Data Visualization

Plotting a simple bar chart

```{r}
#| echo: false
ggplot(data = exam_data,
       aes(x = RACE)) + 
  geom_bar(fill = "steelblue4", color = "grey40") +
  labs(
    x = "Race",
    y = "Number of Students"
  ) +
  theme(
    panel.background = element_rect(fill = "white")
  )
```

```{r}
ggplot(data = exam_data,
       aes(x = RACE)) + 
  geom_bar(fill = "steelblue4", color = "grey40") +
  labs(
    x = "Race",
    y = "Number of Students"
  ) +
  theme(
    panel.background = element_rect(fill = "white")
  ) +
  coord_flip()
```

```{r}
ggplot(data=exam_data, 
       aes(x = MATHS)) +
  geom_dotplot(binwidth=2.5,         
               dotsize = 0.5) +      
  scale_y_continuous(NULL,           
                     breaks = NULL)  
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, 
           fill = GENDER)) +
  geom_histogram(bins=20, 
                 color="grey30")
```

```{r}
ggplot(data=exam_data, 
       aes(x = MATHS, 
           colour = GENDER)) +
  geom_density()
```

```{r}
ggplot(data=exam_data, 
       aes(y = MATHS, 
           x= GENDER)) +
  geom_boxplot(notch=TRUE)
```

```{r}
ggplot(data=exam_data, 
       aes(y = MATHS, 
           x= GENDER)) +
  geom_violin()
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, 
           y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              linewidth=0.5)
```

```{r}
ggplot(data=exam_data, 
       aes(y = MATHS, 
           x= GENDER)) +
  geom_boxplot() +                    
  geom_point(position="jitter", 
             size = 0.5)        
```

```{r}
ggplot(data=exam_data, 
       aes(y = MATHS, x= GENDER)) +
  geom_boxplot() +
  geom_point(stat="summary",        
             fun="mean",           
             colour="red",          
             size=4)          
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS)) +
  geom_histogram(bins=20) +
    facet_wrap(~ CLASS)
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS)) +
  geom_histogram(bins=20) +
    facet_grid(~ CLASS)

```
